# **CMPUT 195**: Lab 8

In [2]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Introduction

Welcome to the last lab of Winter 2024! Today, your lab will only consist of a SINGLE output:

#### In total, how many people have attended the Super Bowl in years where the Nobel Prize in Physics was awarded to exactly two laureates?

### To get you started, here's some resources:

1. List of Nobel laureates: https://en.wikipedia.org/wiki/List_of_Nobel_laureates

1. List of Super Bowls: https://en.wikipedia.org/wiki/List_of_Super_Bowl_champions

1. pd.read_html(): A *very* useful function for web scraping.

    Docs: https://pandas.pydata.org/docs/reference/api/pandas.read_html.html

1. str.find(): returns the first index where the specified character is found, or -1 otherwise.

    More info: https://www.w3schools.com/python/ref_string_find.asp

1. df.isna(): returns True if the value is NaN, or False otherwise. Very useful for filtering, because you can call it on an entire Series or DataFrame.

    Docs: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isna.html

### Good luck! Feel free to use other cells or functions as you see fit.

In [51]:
# Start your code here. You should try to break up each step into a new cell if you can.


# URL of the Wikipedia page containing the list of Nobel laureates
url = 'https://en.wikipedia.org/wiki/List_of_Nobel_laureates'

# Use pd.read_html() to scrape the tables from the Wikipedia page
tables = pd.read_html(url, attrs={'class': 'wikitable'})

# The table we're interested in is the first one on the page
nobel_laureates_df = tables[0]

# Filter the Nobel laureates DataFrame for Physics category
physics_laureates_df = nobel_laureates_df[nobel_laureates_df['Physics'].notnull()]

# Extract the year from the "Year" column in the nobel_laureates_df DataFrame
year_series = nobel_laureates_df['Year'].str.extract(r'(\d{4})')

# Add the year column to the physics_laureates_df DataFrame
physics_laureates_df['Year'] = year_series

nobel_physics_df = physics_laureates_df[['Year', 'Physics']]

print(nobel_physics_df)
# Count the number of laureates for each year
nobel_physics_df['Laureate_Count'] = nobel_physics_df['Physics'].apply(lambda x: len(x.split(';')))

# Filter for years where there are exactly two laureates
years_with_two_laureates = nobel_physics_df[nobel_physics_df['Laureate_Count'] == 2]['Year']

print(years_with_two_laureates)

     Year                                           Physics
0    1901                                   Wilhelm RÃ¶ntgen
1    1902                    Hendrik Lorentz; Pieter Zeeman
2    1903        Henri Becquerel; Pierre Curie; Marie Curie
3    1904                                     Lord Rayleigh
4    1905                                    Philipp Lenard
..    ...                                               ...
119  2020    Roger Penrose; Reinhard Genzel; Andrea M. Ghez
120  2021  Giorgio Parisi; Klaus Hasselmann; Syukuro Manabe
121  2022       Alain Aspect; John Clauser; Anton Zeilinger
122  2023   Pierre Agostini; Ferenc Krausz; Anne L'Huillier
123   NaN                                           Physics

[124 rows x 2 columns]
1      1902
8      1909
14     1915
24     1925
26     1927
32     1933
35     1936
36     1937
50     1951
51     1952
53     1954
54     1955
56     1957
58     1959
60     1961
69     1970
73     1974
75     1976
79     1980
82     1983
83     1984
86     1987
92     1993
93     1994
94     1995
98     1999
105    2006
106    2007
109    2010
111    2012
112    2013
114    2015
Name: Year, dtype: object
[1902, 1909, 1915, 1925, 1927, 1933, 1936, 1937, 1951, 1952, 1954, 1955, 1957, 1959, 1961, 1970, 1974, 1976, 1980, 1983, 1984, 1987, 1993, 1994, 1995, 1999, 2006, 2007, 2010, 2012, 2013, 2015]

<ipython-input-51-3b9b5bf22c01>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nobel_physics_df['Laureate_Count'] = nobel_physics_df['Physics'].apply(lambda x: len(x.split(';')))

In [38]:
url = 'https://en.wikipedia.org/wiki/List_of_Super_Bowl_champions'

# Scrape the tables from the Wikipedia page
tables = pd.read_html(url)

# The table
super_bowl_champions_df = tables[1]



# Split the "Date/Season" column into "Date" and "Season"
super_bowl_champions_df[['Date', 'Season']] = super_bowl_champions_df['Date/Season'].str.split('(', expand=True)


# Display the modified DataFrame with the new columns
super_bowl_champions = super_bowl_champions_df[['Date', 'Season', 'Attendance']]

# Create a DataFrame from the provided data
df = pd.DataFrame(super_bowl_champions)

# Extract the year from the 'Date' column
df['Year'] = pd.to_datetime(df['Date']).dt.year

# Select only the 'Year' and 'Attendance' columns
df = df[['Year', 'Attendance']]

print(df)

    Year  Attendance
0   1967       61946
1   1968       75546
2   1969       75389
3   1970       80562
4   1971       79204
5   1972       81023
6   1973       90182
7   1974       71882
8   1975       80997
9   1976       80187
10  1977      103438
11  1978       76400
12  1979       79484
13  1980      103985
14  1981       76135
15  1982       81270
16  1983      103667
17  1984       72920
18  1985       84059
19  1986       73818
20  1987      101063
21  1988       73302
22  1989       75129
23  1990       72919
24  1991       73813
25  1992       63130
26  1993       98374
27  1994       72817
28  1995       74107
29  1996       76347
30  1997       72301
31  1998       68912
32  1999       74803
33  2000       72625
34  2001       71921
35  2002       72922
36  2003       67603
37  2004       71525
38  2005       78125
39  2006       68206
40  2007       74512
41  2008       71101
42  2009       70774
43  2010       74059
44  2011      103219
45  2012       68658
46  2013       71024
47  2014       82529
48  2015       70288
49  2016       71088
50  2017       70807
51  2018       67612
52  2019       70081
53  2020       62417
54  2021       24835
55  2022       70048
56  2023       67827
57  2024       61629

In [53]:
# Convert the array to a list
years_list = years_with_two_laureates.tolist()
years_list = [int(year) for year in years_with_two_laureates]
print(years_list)

# Filter the DataFrame for the years of interest
attendance_df = df[df['Year'].isin(years_list)]
print(attendance_df)

[1902, 1909, 1915, 1925, 1927, 1933, 1936, 1937, 1951, 1952, 1954, 1955, 1957, 1959, 1961, 1970, 1974, 1976, 1980, 1983, 1984, 1987, 1993, 1994, 1995, 1999, 2006, 2007, 2010, 2012, 2013, 2015]
    Year  Attendance
3   1970       80562
7   1974       71882
9   1976       80187
13  1980      103985
16  1983      103667
17  1984       72920
20  1987      101063
26  1993       98374
27  1994       72817
28  1995       74107
32  1999       74803
39  2006       68206
40  2007       74512
43  2010       74059
45  2012       68658
46  2013       71024
48  2015       70288
Total Attendance in the Specified Years: 1361114

In [54]:
# Print your value here. DO NOT hardcode it.
num_attendees = attendance_df['Attendance'].sum()
print(num_attendees)

1361114

## "Question" 2 (Optional):

We'd love to hear your thoughts about your experience in CMPUT 195 this semester. In the markdown cell below, write your favourite part about the course, your least favourite part, what you'd have liked to see more of, or anything else you'd like to say. This isn't for marks, so feel free to skip it if you want to!

## Finishing up

Thanks for being part of the inaugural semester of CMPUT 195! Export this file as a notebook, and submit it on eclass with the name CCID_lab8.ipynb.